import type { Metadata } from "next";
import "@/styles/globals.css";
import ReduxProvider from '@/redux/redux-provider';
import Layout from "@/layout";


export const metadata: Metadata = {
  title: "AI Playground",
  description: "Generated by create next app",
};

type Props = Readonly<{
  children: React.ReactNode;
}>

const RootLayout = ({ children }: Props) => {
  return (
    <html lang="en" className="dark">
      <body className={`antialiased`} suppressHydrationWarning suppressContentEditableWarning>
        <ReduxProvider>
          <Layout>
            {children}
          </Layout>
        </ReduxProvider>
      </body>
    </html>
  );
}

export default RootLayout;